---
AllCops:
  Exclude:
  - Gemfile
  - Rakefile
  - 'test/**/*'
  - 'examples/**/*'
  - 'vendor/**/*'
  - 'lib/bundles/inspec-init/templates/**/*'
  - .direnv/**/*
Documentation:
  Enabled: false
AlignParameters:
  Enabled: true
Encoding:
  Enabled: true
HashSyntax:
  Enabled: true
ClassLength:
  Max: 300
LineLength:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/ReturnInVoidContext:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
  - "test/integration/verify/controls/*"
EmptyLinesAroundBlockBody:
  Enabled: false
MethodLength:
  Max: 45
NumericLiterals:
  MinDigits: 10
Metrics/BlockLength:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 11
Metrics/AbcSize:
  Max: 75
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 25
Naming/AccessorMethodName:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Layout/AlignHash:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Not:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/NegatedIf:
  Enabled: false
Style/UnlessElse:
  Enabled: false
BlockDelimiters:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
